dat50 <- read.table("outPar50seq1mut.txt")
dat10 <- read.table("outPar10seq1mut.txt")
pdf("IS_samples.pdf")
par(mfrow=c(2,2))
plot(dat50$V1[1:1000],xlab="MCMC iteration",ylab="Effective mutation rate",type="l")
plot(dat10$V1[1:1000],xlab="MCMC iteration",ylab="Effective mutation rate",type="l")
hist(dat50$V1,xlab="Effective mutation rate",main="50 Sequences")
hist(dat10$V1,xlab="Effective mutation rate",main="10 Sequences")
dev.off()
